# Generated by Django 3.2.8 on 2022-05-10 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('LoanID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField(null=True, verbose_name='Monto')),
                ('Term', models.IntegerField(null=True, verbose_name='Plazo')),
                ('InterestRate', models.FloatField(null=True, verbose_name='Interes')),
                ('StartDate', models.DateTimeField(null=True, verbose_name='Fecha Inicial')),
                ('monthlyPayment', models.FloatField(null=True, verbose_name='Cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('PeriodicityID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xPayment',
            fields=[
                ('xPaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(null=True, verbose_name='Fecha de Pago')),
                ('Amount', models.FloatField(null=True, verbose_name='Monto')),
                ('LoanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Credit.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Paymant',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(null=True, verbose_name='Fecha de Pago')),
                ('Payment', models.FloatField(null=True, verbose_name='Valor Pago')),
                ('Pricipal', models.FloatField(null=True, verbose_name='Capital')),
                ('Interest', models.FloatField(null=True, verbose_name='Interes')),
                ('Balance', models.FloatField(null=True, verbose_name='Balance')),
                ('LoanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Credit.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='Periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Credit.periodicity'),
        ),
    ]
