# Generated by Django 4.0.4 on 2022-05-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0002_loan_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Amount',
            new_name='Ammount',
        ),
        migrations.AddField(
            model_name='loan',
            name='DisbursementDate',
            field=models.DateField(null=True, verbose_name='Fecha Desembolso'),
        ),
        migrations.AddField(
            model_name='loan',
            name='Name',
            field=models.TextField(max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='StartDate',
            field=models.DateField(null=True, verbose_name='Fecha Inicial'),
        ),
    ]
