# Generated by Django 3.2.8 on 2022-04-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dropay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('LoanID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField(null=True, verbose_name='Monto')),
                ('Term', models.IntegerField(null=True, verbose_name='Plazo')),
                ('InterestRate', models.FloatField(null=True, verbose_name='Interes')),
                ('StartDate', models.DateTimeField(null=True, verbose_name='Fecha Inicial')),
                ('monthlyPayment', models.FloatField(null=True, verbose_name='Cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('PeriodicityID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeID',
            fields=[
                ('TypeIDID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='DateofBirth',
            field=models.DateTimeField(null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=60, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(max_length=25, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='LastName',
            field=models.CharField(max_length=25, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='IdentityDocument',
            field=models.IntegerField(null=True, verbose_name='Documento de Identidad'),
        ),
        migrations.CreateModel(
            name='xPayment',
            fields=[
                ('xPaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(null=True, verbose_name='Fecha de Pago')),
                ('Amount', models.FloatField(null=True, verbose_name='Monto')),
                ('LoanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.loan')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('UserCredentialID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, null=True, verbose_name='Usuario')),
                ('Password', models.CharField(max_length=50, null=True, verbose_name='Contraseña')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paymant',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(null=True, verbose_name='Fecha de Pago')),
                ('Payment', models.FloatField(null=True, verbose_name='Valor Pago')),
                ('Pricipal', models.FloatField(null=True, verbose_name='Capital')),
                ('Interest', models.FloatField(null=True, verbose_name='Interes')),
                ('Balance', models.FloatField(null=True, verbose_name='Balance')),
                ('LoanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='Periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.periodicity'),
        ),
        migrations.AddField(
            model_name='loan',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dropay.typeid'),
        ),
    ]
