# Generated by Django 3.2.8 on 2022-04-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dropay', '0002_auto_20220423_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DateofBirth',
        ),
    ]
