# Generated by Django 3.2.8 on 2022-04-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dropay', '0003_remove_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DateofBirth',
            field=models.DateTimeField(null=True, verbose_name='Cumpleaños'),
        ),
    ]
