# Generated by Django 3.2.8 on 2022-05-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeID',
            fields=[
                ('TypeIDID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdentityDocument', models.IntegerField(null=True, verbose_name='Documento de Identidad')),
                ('DateofBirth', models.DateTimeField(null=True, verbose_name='Cumpleaños')),
                ('TypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.typeid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
