# Generated by Django 3.2.8 on 2022-05-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_typeid_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeid',
            name='Description',
            field=models.CharField(max_length=20, null=True, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='TypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.typeid'),
        ),
    ]
