# Generated by Django 4.0.4 on 2022-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220525_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='IdentityDocument',
            field=models.CharField(max_length=20, null=True, verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='typeid',
            name='Description',
            field=models.CharField(max_length=30, null=True, verbose_name='Document type'),
        ),
    ]
